### ISSUE TITLE
trying to run on Windows 

### ISSUE THREAD

**Issue by frbayart** [spark-notebook/spark-notebook#950] opened 2018-03-23 08:17 UTC
There are some troubles to run ".zip" version on Windows, I will add all message I receive from users in this issue.

Running

- Scala 2.11
- JVM 1.8
- Spark 2.2
- SparkNotebook from `master`

**Comment by frbayart** [comment] 2018-03-23 08:18
```
Error: Could not find or load main class notebook.kernel.pfork.ChildProcessMain
Caused by: java.lang.ClassNotFoundException: notebook.kernel.pfork.ChildProcessMain
2018-03-23 06:59:59 ERROR application:130 - Process exited with an error: 1 (Exit value: 1)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
    at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
    at java.base/java.lang.Thread.run(Thread.java:844)
2018-03-23 07:00:58 ERROR OneForOneStrategy:159 - Futures timed out after [1 minute]
akka.actor.ActorInitializationException: akka://NotebookServer/user/$b: exception during creation
    at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
    at akka.actor.ActorCell.create(ActorCell.scala:607)
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
    at akka.dispatch.Mailbox.run(Mailbox.scala:223)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
    at scala.concurrent.Await$.result(package.scala:190)
    at notebook.Kernel$ExecutionManager.preStart(Kernel.scala:56)
    at akka.actor.Actor$class.aroundPreStart(Actor.scala:510)
    at notebook.Kernel$ExecutionManager.aroundPreStart(Kernel.scala:51)
    at akka.actor.ActorCell.create(ActorCell.scala:590)
    ... 9 more
```

**Comment by frbayart** [comment] 2018-03-23 08:19
```
2018-03-19 11:46:34 WARN  application:111 - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2018-03-19 11:46:35 INFO  Slf4jLogger:92 - Slf4jLogger started
2018-03-19 11:46:35 WARN  application:111 - application.langs is deprecated, use play.i18n.langs instead
2018-03-19 11:46:35 WARN  application:111 - application.conf @ file:/C:/Users/ThomasDH/Downloads/spark-notebook-0.9.0-SNAPSHOT-scala-2.11.8-spark-2.2.0-hadoop-2.7.2/conf/application.conf: 8: application.secret is deprecated, use play.crypto.secret instead
2018-03-19 11:46:35 INFO  Play:92 - Application started (Prod)
2018-03-19 11:46:35 INFO  NettyServer:92 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[DEBUG] [03/19/2018 11:46:44.000] [netty-event-loop-3] [EventStream] StandardOutLogger started
2018-03-19 11:46:44 INFO  Slf4jLogger:92 - Slf4jLogger started
[DEBUG] [03/19/2018 11:46:44.027] [netty-event-loop-3] [EventStream(akka://NotebookServer)] logger log1-Slf4jLogger started
[DEBUG] [03/19/2018 11:46:44.028] [netty-event-loop-3] [EventStream(akka://NotebookServer)] Default Loggers started
2018-03-19 11:46:44 INFO  Remoting:107 - Starting remoting
2018-03-19 11:46:44 INFO  Remoting:107 - Remoting started; listening on addresses :[akka.tcp://NotebookServer@127.0.0.1:23605]
2018-03-19 11:46:44 INFO  Remoting:107 - Remoting now listens on addresses: [akka.tcp://NotebookServer@127.0.0.1:23605]
2018-03-19 11:46:44 INFO  application:92 - io.provider_timeout: 89000 ms
2018-03-19 11:46:44 INFO  application:92 - Notebooks dir is C:\Users\ThomasDH\Downloads\spark-notebook-0.9.0-SNAPSHOT-scala-2.11.8-spark-2.2.0-hadoop-2.7.2\bin\notebooks
2018-03-19 11:46:44 INFO  application:92 - Notebook directory is: C:\Users\ThomasDH\Downloads\spark-notebook-0.9.0-SNAPSHOT-scala-2.11.8-spark-2.2.0-hadoop-2.7.2\bin\notebooks
(projectStore: ,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration),projectManager:,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration))
(projectStore: ,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration),projectManager:,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration))
(projectStore: ,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration),projectManager:,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration))
2018-03-19 11:46:44 INFO  application:92 - listNotebooks at path /
2018-03-19 11:46:52 INFO  application:92 - listNotebooks at path /
2018-03-19 11:46:52 INFO  application:92 - Calling action
2018-03-19 11:46:52 INFO  application:92 - Creating notebook at /
2018-03-19 11:46:52 INFO  application:92 - save at path /Test.snb.ipynb with message None
2018-03-19 11:46:52 ERROR application:140 - 
! @77b3n3cfp - Internal server error, for (POST) [/api/contents/] ->
 
@77b3n3cfp: Unexpected exception
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
    at Global$.onError(Global.scala:5)
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at scala.concurrent.Promise$class.complete(Promise.scala:55)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
    at scala.concurrent.Promise$class.failure(Promise.scala:104)
    at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:153)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:257)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: No copy_from
    at controllers.Application$.controllers$Application$$findkey$1(Application.scala:414)
    at controllers.Application$$anonfun$copyFrom$lzycompute$1$1.apply(Application.scala:428)
    at controllers.Application$$anonfun$copyFrom$lzycompute$1$1.apply(Application.scala:427)
    at scala.util.Success.flatMap(Try.scala:231)
    at controllers.Application$.copyFrom$lzycompute$1(Application.scala:427)
    at controllers.Application$.controllers$Application$$copyFrom$1(Application.scala:426)
    at controllers.Application$$anonfun$newNotebook$1.apply(Application.scala:432)
    at controllers.Application$$anonfun$newNotebook$1.apply(Application.scala:432)
    at scala.util.Try.orElse(Try.scala:84)
    at controllers.Application$.newNotebook(Application.scala:432)
    at controllers.Application$$anonfun$newContent$1$$anonfun$apply$31.apply(Application.scala:457)
    at controllers.Application$$anonfun$newContent$1$$anonfun$apply$31.apply(Application.scala:454)
    at scala.util.Success.flatMap(Try.scala:231)
    at controllers.Application$$anonfun$newContent$1.apply(Application.scala:454)
    at controllers.Application$$anonfun$newContent$1.apply(Application.scala:449)
    at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:371)
    at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:370)
    at controllers.EditorOnlyAction$.invokeBlock(Application.scala:47)
    at controllers.EditorOnlyAction$.invokeBlock(Application.scala:38)
    at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
    at scala.Option.map(Option.scala:146)
    at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
    at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
    ... 14 more
2018-03-19 11:46:52 INFO  application:92 - listNotebooks a
```

**Comment by frbayart** [comment] 2018-03-23 08:20
```
2018-03-13 16:55:21 INFO  application:92 - Spawning calculator in service notebook.server.CalcWebSocketService$CalcActor@7646dce1
Exception in thread "main" java.io.FileNotFoundException: File 'unknown' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
        at notebook.kernel.remote.RemoteActorProcess.init(RemoteActorSystem.scala:29)
        at notebook.kernel.pfork.BetterFork$.doMain(BetterFork.scala:278)
        at notebook.kernel.pfork.BetterFork$.main(BetterFork.scala:228)
        at notebook.kernel.pfork.ChildProcessMain.main(ChildProcessMain.java:5)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1073741824; support was removed in 8.0
2018-03-13 16:55:22 ERROR OneForOneStrategy:159 - Failed to start process [C:\Program Files (x86)\Java\jdk1.8.0_161\jre\bin\java, -Xmx1875378176, -XX:MaxPermSize=1073741824, -server, notebook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 15895, info, f94fa6fe-f50f-4f23-9af6-c84e39d20911, notebooks-training-ml-day1\ml-training\01_scala4spark\Scala4Spark.snb.ipynb, NONE, kernel, , unknown, false] (Exit value: 1. Caused by java.net.SocketException: Connection reset)
akka.actor.ActorInitializationException: akka://NotebookServer/user/$b: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
        at akka.actor.ActorCell.create(ActorCell.scala:607)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.commons.exec.ExecuteException: Failed to start process [C:\Program Files (x86)\Java\jdk1.8.0_161\jre\bin\java, -Xmx1875378176, -XX:MaxPermSize=1073741824, -server, notebook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 15895, info, f94fa6fe-f50f-4f23-9af6-c84e39d20911, notebooks-training-ml-day1\ml-training\01_scala4spark\Scala4Spark.snb.ipynb, NONE, kernel, , unknown, false] (Exit value: 1. Caused by java.net.SocketException: Connection reset)
        at notebook.kernel.pfork.BetterFork$$anonfun$execute$1.apply(BetterFork.scala:145)
        at notebook.kernel.pfork.BetterFork$$anonfun$execute$1.apply(BetterFork.scala:121)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        ... 4 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2653)
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2669)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3146)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:858)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:354)
        at notebook.kernel.pfork.BetterFork$$anonfun$execute$1.apply(BetterFork.scala:147)
        ... 9 more
2018-03-13 16:55:22 ERROR application:130 - Process exited with an error: 1 (Exit value: 1)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by vidma** [comment] 2018-03-25 17:27
at least `SN @ docker on windows` should work if I remember correctly so this is not an urgent issue ?

**Comment by frbayart** [comment] 2018-03-25 17:57
No it's not urgent and I'm working on it (we have Hyper-V and Virtualbox image) and also Docker (but it's not easy to use with specific tools)

**Comment by acrozes** [comment] 2018-06-16 01:34
I also try to run on windows and I have maybe the same error:

```
C:\SparkNotebook>bin\spark-notebook
2018-06-16 03:28:58 WARN  application:111 - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2018-06-16 03:29:06 INFO  Slf4jLogger:92 - Slf4jLogger started
2018-06-16 03:29:06 WARN  application:111 - application.langs is deprecated, use play.i18n.langs instead
2018-06-16 03:29:07 WARN  application:111 - application.conf @ file:/C:/SparkNotebook/conf/application.conf: 8: application.secret is deprecated, use play.crypt
o.secret instead
2018-06-16 03:29:07 INFO  Play:92 - Application started (Prod)
2018-06-16 03:29:11 INFO  AkkaHttpServer:92 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[DEBUG] [06/16/2018 03:29:13.329] [application-akka.actor.default-dispatcher-4] [EventStream] StandardOutLogger started
2018-06-16 03:29:13 INFO  Slf4jLogger:92 - Slf4jLogger started
[DEBUG] [06/16/2018 03:29:13.509] [application-akka.actor.default-dispatcher-4] [EventStream(akka://NotebookServer)] logger log1-Slf4jLogger started
[DEBUG] [06/16/2018 03:29:13.513] [application-akka.actor.default-dispatcher-4] [EventStream(akka://NotebookServer)] Default Loggers started
2018-06-16 03:29:14 INFO  Remoting:107 - Starting remoting
2018-06-16 03:29:14 INFO  Remoting:107 - Remoting started; listening on addresses :[akka.tcp://NotebookServer@127.0.0.1:9929]
2018-06-16 03:29:14 INFO  Remoting:107 - Remoting now listens on addresses: [akka.tcp://NotebookServer@127.0.0.1:9929]
2018-06-16 03:29:15 INFO  application:92 - io.provider_timeout: 89000 ms
2018-06-16 03:29:15 INFO  application:92 - Notebooks dir is C:\SparkNotebook\notebooks
2018-06-16 03:29:15 INFO  application:92 - Notebook directory is: C:\SparkNotebook\notebooks
(projectStore: ,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration),projectManager:,Failure(java.lang.RuntimeException: C
ould not find [sbt-project-generation] configuration))
(projectStore: ,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration),projectManager:,Failure(java.lang.RuntimeException: C
ould not find [sbt-project-generation] configuration))
(projectStore: ,Failure(java.lang.RuntimeException: Could not find [sbt-project-generation] configuration),projectManager:,Failure(java.lang.RuntimeException: C
ould not find [sbt-project-generation] configuration))
2018-06-16 03:29:18 INFO  application:92 - listNotebooks at path core
2018-06-16 03:29:38 INFO  application:92 - listNotebooks at path core
2018-06-16 03:29:38 INFO  application:92 - View notebook 'core\Spark-101.snb.ipynb', presentation: 'None'
2018-06-16 03:29:42 INFO  application:92 - getNotebook at path core\Spark-101.snb.ipynb
2018-06-16 03:29:42 INFO  application:92 - Loading notebook at path core\Spark-101.snb.ipynb
2018-06-16 03:29:42 WARN  ActorSystemImpl:131 - Explicitly set HTTP header 'Content-Type: application/force-download' is ignored, explicit `Content-Type` header
 is not allowed. Set `HttpResponse.entity.contentType` instead.
2018-06-16 03:29:45 INFO  application:92 - Calling action
2018-06-16 03:29:45 INFO  application:92 - createSession for user: None  for NB: Some(core\Spark-101.snb.ipynb)
2018-06-16 03:29:45 INFO  application:92 - Starting kernel/session because nothing for None and Some(core\Spark-101.snb.ipynb)
2018-06-16 03:29:45 INFO  application:92 - Loading notebook at path core\Spark-101.snb.ipynb
2018-06-16 03:29:45 INFO  BetterFork$:122 - Spawning [C:\Program Files\Java\jdk1.8.0_171\jre\bin\java, -Xmx3795845120, -XX:MaxPermSize=1073741824, -server, note
book.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 9939, info, 7a1cf2f6-af39-4920-98f1-0425723ece03, core\Spark-101.snb.ipynb, NONE,
 kernel, , unknown, false]
2018-06-16 03:29:45 INFO  application:92 - Spawning [C:\Program Files\Java\jdk1.8.0_171\jre\bin\java, -Xmx3795845120, -XX:MaxPermSize=1073741824, -server, noteb
ook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 9939, info, 7a1cf2f6-af39-4920-98f1-0425723ece03, core\Spark-101.snb.ipynb, NONE,
kernel, , unknown, false]
2018-06-16 03:29:45 INFO  application:92 - In working directory .
2018-06-16 03:29:46 INFO  application:92 - Registering first web-socket (notebook.server.WebSockWrapperImpl@706d393) in service notebook.server.CalcWebSocketSer
vice$CalcActor@1809f22c
2018-06-16 03:29:46 INFO  application:92 - Spawning calculator in service notebook.server.CalcWebSocketService$CalcActor@1809f22c
Exception in thread "main" java.io.FileNotFoundException: File 'unknown' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
        at notebook.kernel.remote.RemoteActorProcess.init(RemoteActorSystem.scala:29)
        at notebook.kernel.pfork.BetterFork$.doMain(BetterFork.scala:278)
        at notebook.kernel.pfork.BetterFork$.main(BetterFork.scala:228)
        at notebook.kernel.pfork.ChildProcessMain.main(ChildProcessMain.java:5)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1073741824; support was removed in 8.0
2018-06-16 03:29:48 ERROR OneForOneStrategy:159 - Failed to start process [C:\Program Files\Java\jdk1.8.0_171\jre\bin\java, -Xmx3795845120, -XX:MaxPermSize=1073
741824, -server, notebook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 9939, info, 7a1cf2f6-af39-4920-98f1-0425723ece03, core\Spark
-101.snb.ipynb, NONE, kernel, , unknown, false] (Exit value: 1. Caused by java.net.SocketException: Connection reset)
akka.actor.ActorInitializationException: akka://NotebookServer/user/$b: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
        at akka.actor.ActorCell.create(ActorCell.scala:607)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.commons.exec.ExecuteException: Failed to start process [C:\Program Files\Java\jdk1.8.0_171\jre\bin\java, -Xmx3795845120, -XX:MaxPermSize=1
073741824, -server, notebook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 9939, info, 7a1cf2f6-af39-4920-98f1-0425723ece03, core\Sp
ark-101.snb.ipynb, NONE, kernel, , unknown, false] (Exit value: 1. Caused by java.net.SocketException: Connection reset)
        at notebook.kernel.pfork.BetterFork$$anonfun$execute$1.apply(BetterFork.scala:145)
        at notebook.kernel.pfork.BetterFork$$anonfun$execute$1.apply(BetterFork.scala:121)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        ... 4 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2661)
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2677)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3154)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
        at notebook.kernel.pfork.BetterFork$$anonfun$execute$1.apply(BetterFork.scala:147)
        ... 9 more
2018-06-16 03:29:48 ERROR application:130 - Process exited with an error: 1 (Exit value: 1)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        at java.lang.Thread.run(Thread.java:748)

```

Thanks

**Comment by andypetrella** [comment] 2018-06-23 19:20
Can you provide where (the path on the machine) the Spark-Notebook is expanded?

It may contain whitespaces which can cause troubles right now

**Comment by acrozes** [comment] 2018-06-24 17:33
Yes but no whitespace: `C:\SparkNotebook\bin` and `C:\SparkNotebook\notebooks` for notebooks

**Comment by andypetrella** [comment] 2018-06-24 17:40
Mmmmhhhh that would have been an easy one to “fix” ^^

Then it must be something about the backslashes. I will try to find a windows setup to chase this down

**Comment by jbonn4** [comment] 2018-08-16 20:46
@acrozes 

I had this same problem. The issue is that spark-notebook is trying to read a cookie file that does not exist. It can't figure out your user name, so it assigns it the string "unknown" and is trying to read the file "unknown" in the spark-notebook directory.

This is from your stacktrace, notice the "unknown" toward the end of both lines:
```
2018-06-16 03:29:45 INFO  BetterFork$:122 - Spawning [C:\Program Files\Java\jdk1.8.0_171\jre\bin\java, -Xmx3795845120, -XX:MaxPermSize=1073741824, -server, note
book.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 9939, info, 7a1cf2f6-af39-4920-98f1-0425723ece03, core\Spark-101.snb.ipynb, NONE,
 kernel, , unknown, false]
2018-06-16 03:29:45 INFO  application:92 - Spawning [C:\Program Files\Java\jdk1.8.0_171\jre\bin\java, -Xmx3795845120, -XX:MaxPermSize=1073741824, -server, noteb
ook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 9939, info, 7a1cf2f6-af39-4920-98f1-0425723ece03, core\Spark-101.snb.ipynb, NONE,
kernel, , unknown, false]

```
My solution was to just create an empty file named unknown in the spark-notebook base directory.

After that, I had a related error creating the tmp directory (same issue, user name is "unknown"). That can be fixed in the application.conf file in the section by pointing the JVM to a tmp directory that you want to use (and exists):

```
notebooks{
  override{
    args: [ "-Djava.io.tmpdir=wherever/you/want/it/to/be" ]
  }
}
```

That said, the tmp directory does not seem to be getting cleaned up when stopping the session.

Good luck.

**Comment by GabeChurch** [comment] 2018-09-04 19:36
@jbonn4 

Thanks for sharing your solution! Did the trick for me when launching via sbt from "Git Bash for Windows".

**Closed** 2018-12-23 22:06 UTC
Labels: bug, windows-only issue

**Comment by yeikel** [comment] 2019-01-04 01:54
I can confirm this keeps happening (Windows 10)

I tried what @jbonn4  proposed but it does not seem to work for me : 

```
manager {
  viewer_mode = false
  viewer_mode = ${?VIEWER_MODE}

  notebooks {
    ###
    # Server dir (containing notebook files)
    dir = ./notebooks
    dir = ${?NOTEBOOKS_DIR}
    override{
    args: [ "-Djava.io.tmpdir=C:\dev\spark-notebook-0.8.3-scala-2.11.8-spark-2.2.2-hadoop-2.7.2-with-hive\test\" ]
  }

  }
```
